
datadump.location:
  author: C:\Users\siddharth\Downloads\test-authors.txt
  works: C:\Users\siddharth\Downloads\test-works.txt

spring:
  data:
    cassandra:
      keyspace-name: main
      username: ikYQazUPbjwXkhqOQPtxDDeK
      password: dI-WC,xC4g6x,Iqt,eclS-wgs2NiJWGoGjUrRF3lUJRzgxrXA-i-ZFrYgpEALvMJCOgbbNdahuAJePUBXWn6-y_+fzOXKyJsnQ5ifcyyZYQYZ82HFC-tCoD7fvD6yT8X
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  main:
    allow-circular-references: true


datastax.astra:
    secure-connect-bundle: secure-connect-betterreads.zip


astra.db:
    id: 08aa78c5-e53f-474c-8d84-2113750fd383-1
    region: us-east1
    keyspace: main
    application.token: AstraCS:ikYQazUPbjwXkhqOQPtxDDeK:9e68c82167e84f59670a74825fe0a1174160af4dfa11fa81e77eda7376acddb8